export const en = {
  nav: { features: 'Features', download: 'Download', support: 'Support', privacy: 'Privacy' },
  common: { get: 'Get Floatem', explore: 'Explore features', latest: 'Latest release', allThemes: 'Six themes', back: 'Back home' },
  home: {
    eyebrow: 'Floatem · Notes and tasks for your desktop', title: ['Keep ideas close.', 'Keep focus clear.'],
    body: 'Capture notes and tasks, then float what matters on your desktop. It is there when you need it, and quiet when you do not.', note: 'There when you need it.',
    themeTitle: 'Six themes.\nA desktop that fits the moment.', themeBody: 'Classic, Afterglow, Plum, Orchid, Bamboo, and Chrysanthemum — a light backdrop for each kind of focus.',
    flowTitle: 'Capture, float, finish.\nNo constant window switching.', flowBody: 'Keep notes and tasks where they are easy to check. Floatem holds the context without taking your attention.',
    scenes: ['Capture a thought while watching', 'Keep context beside your code', 'Pin a note on your desktop', 'Keep tasks and reminders in view'], closing: 'Keep what matters\nin sight.',
  },
  features: { label: 'Features', title: 'Notes and tasks,\nright where you need them.', intro: 'Quick capture, task organization, and floating cards — keep every detail easy to check.', items: [['01', 'Capture a thought. Stay in your flow.', 'Use a global shortcut or the menu bar to call up Floatem and create a note or task without leaving what you are doing.', 'Quick capture · Groups · Filters · Sorting'], ['02', 'Give every note room to take shape.', 'Use rich text, colors, and collapsible content to keep scattered thoughts clear, editable, and ready for the next pass.', 'Rich text · Color · Collapsible content'], ['03', 'Set a lighter rhythm for the day.', 'Add dates, groups, filters, and reminders to tasks. Every small completion makes the next step easier to see.', 'Dates · Groups · Filters · Reminders'], ['04', 'Pull out what matters.', 'Drag a note or task from the main window into an editable, resizable floating card. Give each task its own place.', 'Floating cards · Editing · Resizing'], ['05', 'Pin it to the desktop — and keep it there.', 'Keep a card on the desktop when it needs to stay in sight. With launch at login enabled, pinned cards can return with your desktop.', 'Desktop pinning · Launch at login · Local storage'], ['06', 'Set the tone for your desktop.', 'Six light themes, Chinese and English interfaces, built-in help, and an interactive guide make the first moments feel natural.', 'Six themes · Chinese & English · In-app guide']] },
  download: { label: 'Download Floatem', title: 'Download it.\nStart capturing.', intro: 'Floatem is ready for the desktop you use every day. Choose a platform to get started.', mac: 'Get it on the Mac App Store', windows: 'The Windows edition is on its way', coming: 'Coming soon', current: 'Current release', update: 'What’s new', requirement: 'Requirements' },
  support: { label: 'Technical support', title: 'Need a hand?\nWe are here.', intro: 'For product questions, feature ideas, or privacy details, send us an email.', contact: 'Contact Floatem', contactTitle: 'Tell us what you are running into.', contactHint: 'Select the address to start an email.', contactTopics: ['Help with Floatem', 'Feature idea', 'Privacy question'], faq: 'Frequently asked questions', questions: [['How do I report a problem?', 'Please include your device, system and Floatem versions, plus short steps that reproduce the issue.'], ['Where can I find the app version?', 'Open the About page in Floatem to see its current version.'], ['Does Floatem sync my data to the cloud?', 'Floatem currently keeps your content on your device. It does not create an account or upload your notes.'], ['When will Windows be available?', 'The Windows edition is in preparation. Email us to be notified when it arrives.']] },
  privacy: { label: 'Privacy policy', title: 'Your thoughts\nbelong to you.', updated: 'Last updated: August 7, 2026', sections: [['What we collect', 'Floatem does not ask you to create an account. Notes, tasks and preferences are stored locally on your device by default. We do not read, sell, or use that content for advertising.'], ['Diagnostic information', 'When you choose to contact support, your email may include device, system, and app-version details that you provide. We use this only to solve issues and improve the app.'], ['Third-party services', 'Downloads may be completed through platforms such as the Apple App Store. Their privacy policies govern their related download, payment, and account information.'], ['Your choices', 'You may remove the app and its local data at any time. Please contact support with any privacy question.']] },
}
