export const en = {
  nav: { features: 'Features', download: 'Download', support: 'Support', privacy: 'Privacy' },
  common: { get: 'Get Floatem', explore: 'Explore features', latest: 'Latest release', allThemes: 'Six themes', back: 'Back home' },
  home: {
    eyebrow: 'Floatem · Notes and tasks for your desktop', title: ['Keep ideas close.', 'Keep focus clear.'],
    body: 'Capture notes and tasks, then float what matters on your desktop. It is there when you need it, and quiet when you do not.', note: 'There when you need it.',
    themeTitle: 'Six themes.\nA desktop that fits the moment.', themeBody: 'Classic, Afterglow, Plum, Orchid, Bamboo, and Chrysanthemum — a light backdrop for each kind of focus.',
    flowTitle: 'Capture, float, finish.\nNo constant window switching.', flowBody: 'Keep notes and tasks where they are easy to check. Floatem holds the context without taking your attention.',
    scenes: ['Capture a thought while watching', 'Keep context beside your code', 'Pin a note on your desktop', 'Keep tasks and reminders in view'], closing: 'Keep what matters\nin sight.',
  },
  features: { label: 'Features', title: 'Notes and tasks,\nright where you need them.', intro: 'Quick capture, task organization, and floating cards — keep every detail easy to check.', items: [['01', 'Shift + Space. Floatem, instantly.', 'Press the default Shift + Space shortcut to bring Floatem’s main window forward the moment an idea appears. Prefer another combination? Change the shortcut in Floatem to one that feels natural to you.', 'In a meeting, while browsing, or mid-draft, capture the thought without switching to another tool. Then shape it with rich text, color, collapsible content, groups, and filters when you are ready.', 'Default Shift + Space · Instant launch · Fully customizable'], ['02', 'Drag it out. Let the card float.', 'Press and drag a note or task from the main window into open space. It becomes an editable, resizable floating card instead of disappearing back into a list.', 'When you are coding, watching a video, or comparing reference material, keep the detail at the edge of your view. It takes less attention than reopening the app or switching windows.', 'Drag out → Float → Keep editing · Resize freely'], ['03', 'Four steps. A task is in.', 'When something needs doing, skip the layers: press Shift + Space to bring up Floatem, press Enter to begin, type the task, then press Enter once more to add it.', 'The entire capture flow is four quick moves — Shift + Space → Enter → type the task → Enter. In a meeting, while browsing, or in the middle of work, turn a thought into a next step immediately; dates, groups, filters, and reminders can shape the plan later.', 'Shift + Space → Enter → Type task → Enter · Dates · Groups · Reminders'], ['04', 'Pin key information to the desktop.', 'Pin an existing floating card to the desktop so it stays above the desktop and behind ordinary windows. With launch at login enabled, pinned cards can return with your desktop.', 'Keep a recurring checklist, project cue, or today’s priority where it cannot be covered by work windows. You will not need to find the same card again.', 'Desktop pinning · Launch at login · Local storage'], ['05', 'Match the desktop you are working in.', 'Choose from six light themes and switch the interface between Chinese and English whenever needed. The theme carries through Floatem’s main working surfaces.', 'Use a different tone for a different kind of focus, so floating cards feel at home beside your desktop. Color helps recognition and calm, not just decoration.', 'Classic · Afterglow · Plum · Orchid · Bamboo · Chrysanthemum'], ['06', 'Start with a clear first step.', 'Open built-in help or the interactive guide, follow the prompts through the basics, then begin making your own notes and tasks. Help remains available inside the app when you need a refresher.', 'Do not spend the first session guessing how floating cards or everyday controls work. Get oriented quickly and return attention to your work.', 'Built-in help · Interactive guide · Chinese & English']] },
  download: { label: 'Download Floatem', title: 'Download it.\nStart capturing.', intro: 'Floatem is ready for the desktop you use every day. Choose a platform to get started.', mac: 'Get it on the Mac App Store', windows: 'The Windows edition is on its way', coming: 'Coming soon', current: 'Current release', update: 'What’s new', requirement: 'Requirements' },
  support: { label: 'Technical support', title: 'Need a hand?\nWe are here.', intro: 'For product questions, feature ideas, or privacy details, send us an email.', contact: 'Contact Floatem', contactTitle: 'Tell us what you are running into.', contactHint: 'Select the address to start an email.', contactTopics: ['Help with Floatem', 'Feature idea', 'Privacy question'], faq: 'Frequently asked questions', questions: [['How do I report a problem?', 'Please include your device, system and Floatem versions, plus short steps that reproduce the issue.'], ['Where can I find the app version?', 'Open the About page in Floatem to see its current version.'], ['Does Floatem sync my data to the cloud?', 'Floatem currently keeps your content on your device. It does not create an account or upload your notes.'], ['When will Windows be available?', 'The Windows edition is in preparation. Email us to be notified when it arrives.']] },
  privacy: { label: 'Privacy policy', title: 'Your thoughts\nbelong to you.', updated: 'Last updated: August 7, 2026', sections: [['What we collect', 'Floatem does not ask you to create an account. Notes, tasks and preferences are stored locally on your device by default. We do not read, sell, or use that content for advertising.'], ['Diagnostic information', 'When you choose to contact support, your email may include device, system, and app-version details that you provide. We use this only to solve issues and improve the app.'], ['Third-party services', 'Downloads may be completed through platforms such as the Apple App Store. Their privacy policies govern their related download, payment, and account information.'], ['Your choices', 'You may remove the app and its local data at any time. Please contact support with any privacy question.']] },
}
