export const en = {
  nav: { features: 'Features', download: 'Download', support: 'Support', privacy: 'Privacy' },
  common: { get: 'Get Floatem', explore: 'Explore features', latest: 'Latest release', allThemes: 'Six themes', back: 'Back home' },
  home: {
    eyebrow: 'A quiet place for thoughts that arrive between moments', title: ['Thoughts,', 'gently afloat.'],
    body: 'Floatem is a floating notes and tasks companion for your desktop. It stays within sight, without getting in your way.', note: 'In sight. Just right.',
    themeTitle: 'Six scenes for\nsix states of mind.', themeBody: 'Plum’s restraint. Orchid’s clarity. Bamboo’s ease. Chrysanthemum’s warmth. Let your desktop breathe with you.',
    flowTitle: 'Keep what matters\nwhere it belongs.', flowBody: 'Write it down. Pull it out. Mark it done. Floatem frees notes and tasks from layers of windows.',
    scenes: ['Catch a thought while watching', 'Keep context beside your code', 'Pin a note on your desktop', 'Never lose a task or reminder'], closing: 'You do not have to remember it all.\nLet Floatem keep it in sight.',
  },
  features: { label: 'Features', title: 'Not another window.\nA better kind of company.', intro: 'Floatem keeps information at the right distance — visible, reachable, and quiet.', items: [['01', 'Floating notes', 'Write down a thought, then gently pull it out. It stays with you while you browse, write, or meet.'], ['02', 'Tasks & reminders', 'Set a lighter rhythm for the day. Finish one thing, and the world gets a little clearer.'], ['03', 'Multi-card flow', 'Different work deserves different places. Keep the context that matters in view together.'], ['04', 'Six desktop themes', 'Color is not decoration; it is a vessel for mood. Find the backdrop that fits your focus.']] },
  download: { label: 'Download Floatem', title: 'Begin with\na blank card.', intro: 'Made for the desktop you use every day. Pick a platform and begin.', mac: 'Get it on the Mac App Store', windows: 'The Windows edition is on its way', coming: 'Coming soon', current: 'Current release', update: 'What’s new', requirement: 'Requirements' },
  support: { label: 'Technical support', title: 'Here to keep\nyour thoughts moving.', intro: 'Questions, ideas, or a little friction? Write to us. Every message is read with care.', contact: 'Contact support', faq: 'Frequently asked questions', questions: [['How do I report a problem?', 'Please include your device, system and Floatem versions, plus short steps that reproduce the issue.'], ['Where can I find the app version?', 'Open the About page in Floatem to see its current version.'], ['Does Floatem sync my data to the cloud?', 'Floatem currently keeps your content on your device. It does not create an account or upload your notes.'], ['When will Windows be available?', 'The Windows edition is in preparation. Email us to be notified when it arrives.']] },
  privacy: { label: 'Privacy policy', title: 'Your thoughts\nbelong to you.', updated: 'Last updated: August 7, 2026', sections: [['What we collect', 'Floatem does not ask you to create an account. Notes, tasks and preferences are stored locally on your device by default. We do not read, sell, or use that content for advertising.'], ['Diagnostic information', 'When you choose to contact support, your email may include device, system, and app-version details that you provide. We use this only to solve issues and improve the app.'], ['Third-party services', 'Downloads may be completed through platforms such as the Apple App Store. Their privacy policies govern their related download, payment, and account information.'], ['Your choices', 'You may remove the app and its local data at any time. Please contact support with any privacy question.']] },
}
